export const renderJoin = (req, res) => res.send("Join")
export const renderLogin = (req, res) => res.send("Login")
export const renderLogout = (req, res) => res.send("Logout")
export const renderUsers = (req, res) => res.send("Users")
export const renderUserDetail = (req, res) => res.send("User Detail")
export const renderEditProfile = (req, res) => res.send("Edit Profile")
export const renderChangePassword = (req, res) => res.send("Change Password")