export const renderHome = (req, res) => res.send("Home")
export const renderSearch = (req, res) => res.send("Search")
export const renderVideos = (req, res) => res.send("Videos")
export const renderUpload = (req, res) => res.send("Upload")
export const renderVideoDetail = (req, res) => res.send("Video Detail")
export const renderEditVideo = (req, res) => res.send("Edit Video")
export const renderDeleteVideo = (req, res) => res.send("Delete Video")
